export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  SECURITY_DASHBOARD: '/security-dashboard',
  QUALITY_CHECK_DASHBOARD: '/quality-check-dashboard',
  QUALITY_CHECK_INSPECTION: '/quality-check-dashboard/quality-check-inspection/:inspectionId',
  SERVICE_ADVISOR_DASHBOARD: '/service-advisor-dashboard',
  SERVICE_ADVISOR_VEHICLE_DETAIL: '/service-advisor-dashboard/vehicle/:id',
  CUSTOMER_APPROVAL_DASHBOARD: '/customer-approval-dashboard',
  CUSTOMER_PROFILE_DASHBOARD: '/customer-profile-dashboard',
  SPARE_PARTS_DASHBOARD: '/spare-parts-dashboard',
  TECHNICIAN_DASHBOARD: '/technician-dashboard',
  TECHNICIAN_JOB_DETAIL: '/technician-dashboard/job/:id',
  PROFILE: '/profile',
  ADD_CUSTOMER: '/security-dashboard/add-customer',
  ADD_VEHICLE: '/security-dashboard/add-vehicle',
  VEHICLE_ENTRY_SUCCESS: '/security-dashboard/vehicle-entry-success',
  CREATE_JOB_CARD: '/service-advisor-dashboard/job-card/:vehicleId',
  JOB_CARD_DETAIL: '/service-advisor-dashboard/job-card-detail/:jobCardId',
  FINANCE_BILLING_DASHBOARD: '/finance-billing-dashboard',
  POST_SERVICE_QC_DASHBOARD: '/post-service-qc-dashboard',
  SETTINGS: '/settings',
  CUSTOMER_APPROVAL: '/customer-approval/:token',
  USER_MANAGEMENT: '/user-management',
  QC_OUT_DASHBOARD: '/qc-out-dashboard',
  QC_OUT_INSPECTION: '/qc-out-dashboard/inspection/:vehicleId',
  APPOINTMENT_DASHBOARD: '/appointment-dashboard',
  APPOINTMENT_CREATE_CUSTOMER: '/appointment-dashboard/create/customer',
  APPOINTMENT_CREATE_VEHICLE:  '/appointment-dashboard/create/vehicle',
  APPOINTMENT_CREATE_SERVICE:  '/appointment-dashboard/create/service',
  APPOINTMENT_CREATE_SLOT:     '/appointment-dashboard/create/slot',
  APPOINTMENT_CREATE_REVIEW:   '/appointment-dashboard/create/review',
  APPOINTMENT_CREATE_SUCCESS:  '/appointment-dashboard/create/success',
  VEHICLE_360_DASHBOARD: '/vehicle-360-dashboard',
  VEHICLE_360_DETAIL: '/vehicle-360-dashboard/:vehicleId',
  NO_ACCESS: '/no-access',
};

export default ROUTES;
